### ISSUE TITLE
отсутствие перспективы у штор и окна

### ISSUE THREAD

**Issue by hiucko** [fospas/Space-Cats-14#442]
### Описание

У раздвижного направленного окна и у пластиковых штор спрайт не нарисован в перспективе остальных спрайтов. Это вид сверху, а не перспектива.

### Скриншоты

![IMG-20241003-WA0002_edit_525011815044720](https://github.com/user-attachments/assets/b7086b58-fc2e-44c8-9407-895ec017e772)

**Comment by CrimeMoot** [comment]
С этим остаётся только жить.
