### ISSUE TITLE
Отсутствие перспективы спрайтов

### ISSUE THREAD

**Issue by hiucko** [fospas/Space-Cats-14#560]
### Описание

У многих спрайтов структур отсутствует перспектива, или перспектива отличается от перспективы большинства спрайтов.

### Шаги воспроизведения

1. В панели спавна введите "Wall", "Window"
2. Заспавните объект
3. Посмотрите на его спрайт

### Скриншоты

![изображение](https://github.com/user-attachments/assets/f0338045-7d24-4636-9424-cbd98089fb7f)

**Comment by CrimeMoot** [comment]
я запомню с какими спратйами проблема на этом пока всё.
